CREATE TABLE PERSON(
    PERSON_ID SERIAL PRIMARY KEY,
    PERSON_NAME VARCHAR(32) UNIQUE,
    PERSON_GENDER VARCHAR(32) NOT NULL,
    PERSON_AGE INTEGER DEFAULT 0
);
CREATE TABLE THING(
    THING_ID SERIAL PRIMARY KEY,
    THING_SIZE INTEGER DEFAULT 0,
    THING_TYPE VARCHAR(32) NOT NULL
);
CREATE TABLE SPACESHIP(
    SPACESHIP_ID SERIAL PRIMARY KEY,
    SPACESHIP_SIZE INTEGER DEFAULT 0,
    SPACESHIP_NAME VARCHAR(32) UNIQUE,
    SPACESHIP_TYPE VARCHAR(32) NOT NULL
);
CREATE TABLE SOLUTION(
    SOLUTION_ID SERIAL PRIMARY KEY,
    SOLUTION_TYPE VARCHAR(32) NOT NULL
);
CREATE TABLE SOLVE(
    ID_PERSON INTEGER REFERENCES PERSON,
    ID_SOLUTION INTEGER REFERENCES SOLUTION,
    PRIMARY KEY(ID_PERSON, ID_SOLUTION),
    SOLVE_LASTING VARCHAR(32) NOT NULL
);
CREATE TABLE DISCOVER(
    ID_PERSON INTEGER REFERENCES PERSON,
    ID_THING INTEGER REFERENCES THING,
    ID_SPACESHIP INTEGER REFERENCES SPACESHIP,
    PRIMARY KEY(ID_PERSON, ID_THING, ID_SPACESHIP),
    DISCOVER_LASTING VARCHAR(32) NOT NULL
);
CREATE TABLE LOGICCHAIANS(
    LC_ID SERIAL PRIMARY KEY,
    LC_TYPE VARCHAR(32) NOT NULL,
    ID_SOLUTION INTEGER REFERENCES SOLUTION
);

INSERT INTO PERSON(PERSON_NAME, PERSON_GENDER, PERSON_AGE)
VALUES('ANNA', 'FEMALE', 21),
      ('GEOGE', 'MALE', 23),
      ('JOHN', 'MALE', 22);

INSERT INTO THING(THING_SIZE, THING_TYPE)
VALUES(60, 'CUBE'),
      (88, 'CONE'),
      (77, 'TRANGLE');

INSERT INTO SPACESHIP(SPACESHIP_SIZE, SPACESHIP_NAME, SPACESHIP_TYPE)
VALUES(800, 'SAIER', 'ALLOY'),
      (1100, 'TOMORROW', 'CARBONFIBER'),
      (5000, 'NOAH', 'ALLOY');

INSERT INTO SOLUTION(SOLUTION_TYPE)
VALUES('ADVENTURE'),
      ('INSURANCE'),
      ('COMPROMISE');

INSERT INTO SOLVE(ID_PERSON, ID_SOLUTION, SOLVE_LASTING)
VALUES(1, 2, '14min'),
      (2, 1, '40min'),
      (3, 3, '5min');

INSERT INTO DISCOVER(ID_PERSON, ID_THING, ID_SPACESHIP, DISCOVER_LASTING)
VALUES(1, 2, 3, '20min'),
      (2, 1, 2, '65min'),
      (3, 3, 1, '77min');

INSERT INTO LOGICCHAIANS(LC_TYPE, ID_SOLUTION)
VALUES('FAST', 1),
      ('SLOWLY', 2),
      ('COMMON', 3);