CREATE INDEX IND_ORDER_EMPLOYEE ON "order"(empolyee_id);
CREATE INDEX IND_LOGIN0_CLIENT ON LOGIN0(CLIENT_ID);
CREATE INDEX IND_STORE_SUP ON STOREHOUSE(SUPPLIER_ID);
CREATE INDEX IND_STORE_WHOLE ON STOREHOUSE(WHOLESALER_ID);
CREATE INDEX IND_SELF_ONLINE ON SELF_SALE(ONLINE_STORE_ID);
CREATE INDEX IND_SELF_OFFLINE ON SELF_SALE(OFFLINE_STORE_ID);



SELECT * FROM "order"
INNER JOIN EMPOLYEE ON "order".EMPOLYEE_ID = EMPOLYEE.ID
WHERE EMPOLYEE.ID = 777777;

SELECT LOGIN0.CODE FROM LOGIN0
RIGHT JOIN CLIENT ON CLIENT.ID = LOGIN0.CLIENT_ID
WHERE CLIEND.ID = 198989;

SELECT STOREHOUSE.SELF_SALE_ID, SUPPLIER.NAME AS sup_name, WHOLESALER.NAME as whole_name
FROM WHOLESALER
INNER JOIN STOREHOUSE ON WHOLESALER.ID = STOREHOUSE.WHOLESALER_ID
INNER JOIN SUPPLIER ON STOREHOUSE.SUPPLIER_ID = SUPPLIER.ID
WHERE SUPPLIER.ID = 654364;

EXPLAIN ANALYZE
SELECT SELF_SALE.ID AS SS_ID, OFFLINE_STORE.ADRESS AS OFF_ADRESS, ONLINE_STORE.ADRESS AS ON_ADRESS, OFFLINE_STORE.ID AS OFF_ID
FROM  ONLINE_STORE
INNER JOIN SELF_SALE ON ONLINE_STORE.ID = SELF_SALE.ONLINE_STORE_ID
INNER JOIN OFFLINE_STORE ON SELF_SALE.OFFLINE_STORE_ID = OFFLINE_STORE.ID
WHERE ONLINE_STORE.ID = 123452;
